server:
  port: 8098
  max-http-header-size: 10240
#  servlet:
#    context-path: /apps/gun-test/

envoy:
  httpclient:
    pool-size: 50
    buffer-size: 8192
    timeout: 10000
    compress: true
  app:
    id: 5853afb3000d99aefc73571ea3bedf24
    secret: 1f6f5baa94a7c6874b4258cb8266705e

guns:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  mapper-locations: classpath:cn/stylefeng/guns/modular/**/mapping/*.xml

log:
  path: guns-logs