# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${BUILTIN_APP_MYSQL_SERVICE_HOST:192.168.14.69}:${BUILTIN_APP_MYSQL_SERVICE_PORT:3306}/${APP_MYSQL_DATABASE:guns}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: ${APP_MYSQL_USERNAME:root}
    password: ${APP_MYSQL_PASSWORD:123456}
    filters: wall,mergeStat
    data-source-name: gunsdb

# 多数据源情况的配置
guns:
  muti-datasource:
    open: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guns_test_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    data-source-name: otherdb
